hero.moveUp();
hero.moveLeft();
hero.use("switch")
hero.jumpLeft();
hero.use("door");
hero.moveUp(2);
hero.jumpRight();
hero.use("lever");
hero.moveRight(2);
hero.moveUp(2);
hero.jumpLeft()
hero.moveLeft(1);